services:
  backend:
    build:
      context: ./backend
    container_name: tourhub-backend
    ports:
      - "8000:8000"

    environment:
      DATABASE__URL: postgresql+psycopg://tourhub:tourhub@postgres:5432/tourhub
      REDIS__URL: redis://redis:6379/0

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

    volumes:
      - ./backend/app:/app/app


  postgres:
    image: postgres:18
    container_name: tourhub-postgres

    restart: always

    environment:
      POSTGRES_USER: tourhub
      POSTGRES_PASSWORD: tourhub
      POSTGRES_DB: tourhub

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tourhub -d tourhub"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

    volumes:
      - postgres18_cluster_data:/var/lib/postgresql


  redis:
    image: redis:8-alpine
    container_name: tourhub-redis

    restart: always

    ports:
      - "6379:6379"


  frontend:
    build:
      context: ./frontend

    container_name: tourhub-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

    volumes:
      - ./frontend:/app
      - /app/node_modules


volumes:
  postgres18_cluster_data:
