from io import BytesIO
from datetime import datetime, timezone
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from app.engines.documents.dto import (
    GeneratedDocument,
    PurchaseDocumentDTO,
)


class PDFDocumentGenerator:
    """Generate ERP-style PDF purchase documents."""

    def _register_font(self) -> str:
        font_name = "TourHubUnicode"

        try:
            pdfmetrics.getFont(font_name)
            return font_name
        except KeyError:
            pass

        font_candidates = [
            Path("C:/Windows/Fonts/arial.ttf"),
            Path("C:/Windows/Fonts/calibri.ttf"),
            Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"),
            Path("/usr/share/fonts/dejavu/DejaVuSans.ttf"),
        ]

        for font_path in font_candidates:
            if font_path.exists():
                pdfmetrics.registerFont(
                    TTFont(font_name, str(font_path))
                )
                return font_name

        raise RuntimeError(
            "Unicode PDF font not found. Install a font with Cyrillic support."
        )

    def _footer(self, canvas, document):
        canvas.saveState()
        canvas.setFont("TourHubUnicode", 8)
        canvas.drawString(
            20 * mm,
            10 * mm,
            "Generated by TourHub ERP",
        )
        canvas.drawRightString(
            190 * mm,
            10 * mm,
            f"Page {canvas.getPageNumber()}",
        )
        canvas.restoreState()

    def generate(
        self,
        document: PurchaseDocumentDTO,
    ) -> GeneratedDocument:
        buffer = BytesIO()
        font_name = self._register_font()

        pdf = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=20 * mm,
            leftMargin=20 * mm,
            topMargin=20 * mm,
            bottomMargin=20 * mm,
        )

        styles = getSampleStyleSheet()
        for style in styles.byName.values():
            style.fontName = font_name

        content = []

        content.append(Paragraph(document.title, styles["Title"]))
        content.append(Spacer(1, 10 * mm))

        content.append(
            Paragraph(
                f"Document ID: {document.purchase_list_id}",
                styles["Normal"],
            )
        )
        content.append(Spacer(1, 5 * mm))

        table_data = [
            [
                "Product",
                "Quantity",
                "Unit",
                "Package size",
                "Packages",
            ]
        ]

        for item in document.items:
            table_data.append(
                [
                    item.product_name,
                    str(item.quantity),
                    item.unit,
                    str(item.package_size or "-"),
                    str(item.packages_count or "-"),
                ]
            )

        table = Table(table_data, repeatRows=1)
        table.setStyle(
            TableStyle(
                [
                    ("FONT", (0, 0), (-1, -1), font_name, 9),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
        )

        content.append(table)

        pdf.build(
            content,
            onFirstPage=self._footer,
            onLaterPages=self._footer,
        )

        return GeneratedDocument(
            filename="purchase_list.pdf",
            content_type="application/pdf",
            generated_at=datetime.now(timezone.utc),
            content=buffer.getvalue(),
        )
