"""add meal plan domain

Revision ID: 74d17f270bc5
Revises: 0d101bb77375
Create Date: 2026-07-07 09:13:45.859208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d17f270bc5'
down_revision: Union[str, Sequence[str], None] = '0d101bb77375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('participants', sa.Integer(), nullable=False),
    sa.Column('days_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plan_days',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meal_plan_id', sa.String(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plan_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meal_plan_day_id', sa.String(), nullable=False),
    sa.Column('dish_id', sa.String(), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['meal_plan_day_id'], ['meal_plan_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_plan_items')
    op.drop_table('meal_plan_days')
    op.drop_table('meal_plans')
    # ### end Alembic commands ###
